api:

  common:
    version: 1.0.0
    title: Sample API
    description: Description of the API...
    termsOfServiceUrl: MINE TERMS OF SERVICE URL
    license: License
    licenseUrl: MY LICENSE URL

    contact:
      name: Jelena Petrovački
      url: https://github.com/jelenapetrovacki
      email: jelenapetrovacki@uns.ac.rs

  meal-composite:

    get-composite-meal:
      description: Returns a composite view of the specified meal id
      notes: |
        # Normal response
        If the requested meal id is found the method will return information regarding:
        1. Base meal information
        1. Comments
        1. Recommended drinks
        1. Ingredients
        1. Service Addresses\n(technical information regarding the addresses of the microservices that created the response)
        
        # Expected partial and error responses
        1. If no product information is found, a <b>404 - Not Found</b> error will be returned
        1. In no recommendations or reviews are found for a product, a partial response will be returned
        
    create-composite-meal:
      description: Creates a composite meal
      notes: |
        # Normal response
        The composite meal information posted to the API will be splitted up and stored as separate meal-info, ingredient, recommended drink and comment entities.
        # Expected error responses
        1. If a meal with the same mealId as specified in the posted information already exists,
           an <b>422 - Unprocessable Entity</b> error with a "duplicate key" error message will be returned

    delete-composite-meal:
      description: Deletes a meal composite
      notes: |
        # Normal response
        Entities for meal information, recommended drinks, ingredients and comments related to the specificed mealId will be deleted.
        The implementation of the delete method is idempotent, i.e. it can be called several times with the same response.
        This means that a delete request of a non existing meal will return <b>200 Ok</b>.
        
server.port: 7000
server.error.include-message: always

spring.application.name: meal-composite

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

ribbon.ServerListRefreshInterval: 5000

ribbon.NFLoadBalancerPingInterval: 5

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings:
    output-meals:
      destination: meals
      producer:
        required-groups: auditGroup
    output-recommendedDrinks:
      destination: recommendedDrinks
      producer:
        required-groups: auditGroup
    output-ingredients:
      destination: ingredients
      producer:
        required-groups: auditGroup
    output-comments:
      destination: comments
      producer:
        required-groups: auditGroup

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

logging:
  level:
    root: INFO
    se.magnus: DEBUG

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
    
---
spring.profiles: docker

server.port: 8081

eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/

spring.rabbitmq.host: rabbitmq

spring.cloud.stream.kafka.binder.brokers: kafka